[package]
name = "hob_ecs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
specs = "*"

hob_server.workspace = true
hob_protocol.workspace = true
log.workspace = true
tokio.workspace = true